title = "Vehicle fault table"  #当前VCU故障和冗余制动协议上报的故障


#table 故障名称
#mainCode uint32，
#auto_recovery 自动驾驶模式故障是否可自行恢复 可恢复/不可恢复 0/1
#fault_level 数组, 依次代表自动驾驶模式, 人工驾驶模式, 遥控驾驶模式下的故障等级。车载故障分为1~3级，1级为致命。-1代表该驾驶模式不诊断此故障
#sub_code 数组,每一个字符串代表一个子故障, 每个子故障都标注描述, 子故障的值取用数组的index(1-全F)来代表，0代表默认值

#-----------------------------------------[VCU,offset_HU16=0x0000]------------------------------------------#

#-----------------------------------------[AID,offset_HU16=0x3F00]------------------------------------------#
[[AID]] # 冗余制动供电异常
mainCode = 0x3F000001
auto_recovery = 0
fault_level = [2, 3, 3]

# 排查建议: 1, 查看制动腿供电开关 2, 查看供电灯状态

[[AID]] # 冗余制动自检状态异常
mainCode = 0x3F000002
auto_recovery = 0
fault_level = [2, 3, 3]

# 排查建议: 1, 重启制动腿  2, 记录设备日志，联系艾尔厂家

[[AID]] # 冗余制动腿模式异常或故障
mainCode = 0x3F000003
auto_recovery = 0
fault_level = [2, 3, 3]