#本配置文件仅适用于“徐工DR100车型无人驾驶系统适配开发项目”，其中CCU_Todo的内容需要研发人员评估是否需要填写以及负责填写
#为什么使用toml做故障表, 1:支持读取注释; 2:语法简单, 可读性高, 便于维护;
#为什么独立出Vehicle_fault.toml:都是外部设备上报的显式故障，基本没有subCode可供填充
title = "Vehicle fault table"  #当前VCU故障和冗余制动协议上报的故障


#table 故障名称
#mainCode uint32，
#auto_recovery 自动驾驶模式故障是否可自行恢复 可恢复/不可恢复 0/1
#fault_level 数组, 依次代表自动驾驶模式, 人工驾驶模式, 遥控驾驶模式下的故障等级。车载故障分为1~3级，1级为致命。-1代表该驾驶模式不诊断此故障
#sub_code 数组,每一个字符串代表一个子故障, 每个子故障都标注描述, 子故障的值取用数组的index(1-全F)来代表，0代表默认值

#-----------------------------------------[VCU,offset_HU16=0x0000]------------------------------------------#

#-----------------------------------------[AID,offset_HU16=0x3F00]------------------------------------------#
[EBR_ExtPowerStatus] # 冗余制动供电异常
mainCode = 0x3F000001
auto_recovery = 0
fault_level = [2, 3, 3]

# 排查建议: 1, 查看制动腿供电开关 2, 查看供电灯状态

[EBR_SelfCheckStatus] # 冗余制动自检状态异常
mainCode = 0x3F000002
auto_recovery = 0
fault_level = [2, 3, 3]

# 排查建议: 1, 重启制动腿  2, 记录设备日志，联系艾尔厂家

[EBR_System_Mode] # 冗余制动腿模式异常或故障
mainCode = 0x3F000003
auto_recovery = 0
fault_level = [2, 3, 3]

# 排查建议: 1, 重启制动腿  2, 记录设备日志，联系艾尔厂家
sub_code = [
    "系统异常工作", 
    "故障", 
]


#-----------------------------------------[XCMG,offset_HU16=0x3400]------------------------------------------#
[AirFilterBlock_1] # 空滤器堵塞报警1
mainCode = 0x34000065
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AirFilterBlock_2] # 空滤器堵塞报警2
mainCode = 0x34000066
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AirFilterBlock_3] # 空滤器堵塞报警3
mainCode = 0x34000067
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AirFilterBlock_4] # 空滤器堵塞报警4
mainCode = 0x34000068
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AirFilterBlock_5] # 空滤器堵塞报警5
mainCode = 0x34000069
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AirFilterBlock_6] # 空滤器堵塞报警6
mainCode = 0x3400006a
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[FuelTankLevelLow] # 燃油油位低报警
mainCode = 0x3400006b
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[EngineYellowAlarm] # 发动机黄灯报警
mainCode = 0x3400006c
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[OverloadAlarm] # 超载报警
mainCode = 0x3400006d
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG


[TyreTemperatureHigh_1] # 轮胎温度高报警1
mainCode = 0x3400006e
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_1] # 轮胎胎压高报警1
mainCode = 0x3400006f
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_1] # 轮胎胎压低报警1
mainCode = 0x34000070
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyreTemperatureHigh_2] # 轮胎温度高报警2
mainCode = 0x34000071
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_2] # 轮胎胎压高报警2
mainCode = 0x34000072
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_2] # 轮胎胎压低报警2
mainCode = 0x34000073
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyreTemperatureHigh_3] # 轮胎温度高报警3
mainCode = 0x34000074
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_3] # 轮胎胎压高报警3
mainCode = 0x34000075
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_3] # 轮胎胎压低报警3
mainCode = 0x34000076
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyreTemperatureHigh_4] # 轮胎温度高报警4
mainCode = 0x34000077
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_4] # 轮胎胎压高报警4
mainCode = 0x34000078
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_4] # 轮胎胎压低报警4
mainCode = 0x34000079
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyreTemperatureHigh_5] # 轮胎温度高报警5
mainCode = 0x3400007a
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_5] # 轮胎胎压高报警5
mainCode = 0x3400007b
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_5] # 轮胎胎压低报警5
mainCode = 0x3400007c
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyreTemperatureHigh_6] # 轮胎温度高报警6
mainCode = 0x3400007d
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureHigh_6] # 轮胎胎压高报警6
mainCode = 0x3400007e
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TyrePressureLow_6] # 轮胎胎压低报警6
mainCode = 0x3400007f
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[CoolantTemperatureHigh] # 冷却水温高报警
mainCode = 0x34000097
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[WaterTankLevelLow] # 水箱水位低报警
mainCode = 0x34000099
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[EngineRedAlarm] # 发动机红灯报警
mainCode = 0x340000b5
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[EngineWriteAlarm] # 发动机白灯报警
mainCode = 0x340000b5
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[DoorAjarAlarm] # 车门未关闭报警
mainCode = 0x340000c9
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[SeatBeltAlarm] # 安全带未系报警
mainCode = 0x340000ca
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[FLSuspensionSensorFailure] # 前左悬挂传感器故障
mainCode = 0x340000cb
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[FRSuspensionSensorFailure] # 前右悬挂传感器故障
mainCode = 0x340000cc
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[RLSuspensionSensorFailure] # 后左悬挂传感器故障
mainCode = 0x340000cd
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[RRSuspensionSensorFailure] # 后右悬挂传感器故障
mainCode = 0x340000ce
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[SystemVoltageLow] # 系统电压低
mainCode = 0x340000d0
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ConsoleBoardCANFailure] # 总线键盘CAN故障
mainCode = 0x340000d2
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[VehicleInstrumentCANFailure] # 12.3仪表CAN故障
mainCode = 0x340000d3
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[GPSCANFailure] # GPS CAN故障
mainCode = 0x340000d4
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[DataRecorderCANFailure] # 数据记录仪CAN故障
mainCode = 0x340000db
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[TiltSensorFailure] # 倾角仪错误报警
mainCode = 0x340000dd
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG


[MasterControllerCANFailure] # 主控制器CAN故障
mainCode = 0x340000d5
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[HydraulicControllerCANFailure] # 液压控制器CAN故障
mainCode = 0x340000d6
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AuxiliaryControllerCANFailure] # 辅助控制器CAN故障
mainCode = 0x340000d7
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[SecuritySystemCANFailure] # 安防系统CAN故障
mainCode = 0x340000d8
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[GearboxCANFailure] # 变速箱CAN故障
mainCode = 0x340000d9
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[EngineCANFailure] # 发动机CAN故障
mainCode = 0x340000fc
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[SystemVoltageHigh] # 系统电压高
mainCode = 0x34000118
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[CentralLubricationSystemFailure] # 集中润滑系统故障
mainCode = 0x34000138
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LiftFilterBlock] # 举升回油过滤器堵塞报警
mainCode = 0x3400013f
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[OilWaterSeparationSwitch] # 油水分离水位开关报警
mainCode = 0x34000140
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[LowHydraulicOil] # 液压油位低报警
mainCode = 0x34000142
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[LowSteeringAccumulatorPressure] # 转向蓄能器压力低报警
mainCode = 0x34000162
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[HighHydraulicOilTemperature] # 液压油温高报警
mainCode = 0x34000167
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[LowLoadingBrakePressure] # 装载制动压力低报警
mainCode = 0x34000168
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[FrontAxleBrakeAccumulatorPressureLow] # 前桥制动蓄能器压力低报警
mainCode = 0x34000169
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[RearAxleBrakeAccumulatorPressureLow] # 后桥制动蓄能器压力低报警
mainCode = 0x3400016a
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[LowFrontBrakeCoolingTemperature] # 前制动冷却温度低报警
mainCode = 0x3400016b
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LowRearBrakeCoolingTemperature] # 后制动冷却温度低报警
mainCode = 0x3400016c
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[HighFrontBrakeCoolingTemperature] # 前制动冷却温度高报警
mainCode = 0x3400016d
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[HighRearBrakeCoolingTemperature] # 后制动冷却温度高报警
mainCode = 0x3400016e
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[SteeringPressureLow] # 转向器压力低报警
mainCode = 0x3400016f
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[BrakeOilTemperatureLowerZero] # 制动油温度低于0度报警
mainCode = 0x34000171
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[RetarderOilTemperatureHigh] # 缓速器油温高报警
mainCode = 0x34000172
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[SteeringOilFilterBlock] # 转向回油过滤器堵塞报警
mainCode = 0x34000174
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[SteeringOilTemperatureHighSwitch] # 转向油温高开关报警
mainCode = 0x34000175
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[WetDiscBrakeOilTemperatureHighSwitch] # 湿盘制动油温高开关报警
mainCode = 0x34000176
auto_recovery = 0
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LRearAxleBrakeDiscTemperatureHigh] # 后桥刹车盘温度高报警(左)
mainCode = 0x3400017e
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[RRearAxleBrakeDiscTemperatureHigh] # 后桥刹车盘温度高报警(右)
mainCode = 0x3400017f
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LowFrontAxleBrakePressure] # 前桥制动压力低报警
mainCode = 0x34000180
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LowRearAxleBrakePressure] # 后桥制动压力低报警
mainCode = 0x34000181
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG


[AbnormalRearBrakePressure] # 后制动压力异常
mainCode = 0x34000191
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AbnormalFrontBrakePressure] # 前制动压力异常
mainCode = 0x34000192
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AbnormalHeartbeatOfPC] # PC心跳异常（工控机）
mainCode = 0x34000193
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[APLCModeSwitchError] # APLC模式切换错误
mainCode = 0x34000197
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AbnormalHeartbeatOfBPLC] # BPLC心跳异常
mainCode = 0x34000198
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TimeoutAPLCToBPLC] # APLC与BPLC通讯超时
mainCode = 0x34000199
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TimeoutTrans] # 变速箱通讯超时
mainCode = 0x3400019a
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[TimeoutEngineToAPLC] # 发动机与APLC通讯超时
mainCode = 0x3400019b
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[CargoInclinationSensor] # 货箱倾角传感器故障
mainCode = 0x3400019c
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[CarInclinationSensor] # 车体倾角传感器故障
mainCode = 0x3400019d
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[ModeCmdError] # 模式指令错误
mainCode = 0x3400019e
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ManualAcceleratorIntervention] # 油门人工介入
mainCode = 0x3400019f
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ManualBrakeIntervention] # 制动人工介入
mainCode = 0x340001a0
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ManualGearIntervention] # 档位人工介入
mainCode = 0x340001a1
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[BPLCExit] # BPLC退出无人模式
mainCode = 0x340001a2
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[AbnormalTransMode] # 变速箱模式异常
mainCode = 0x340001a3
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[EngineIgnitionFailure] # 发动机点火失败
mainCode = 0x340001a4
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[EngineShutdownFailure] # 发动机熄火失败
mainCode = 0x340001a5
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[FrontBrakeNotRespond] # 前车制动不响应
mainCode = 0x340001a6
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[RRBrakeNotRespond] # 右后后车制动不响应
mainCode = 0x340001a7
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LRBrakeNotRespond] # 左后后车制动不响应
mainCode = 0x340001a8
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[PoorFrontBrakeResponse] # 前车制动响应差
mainCode = 0x340001a9
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[RRPoorBrakeResponse] # 右后后车制动响应差
mainCode = 0x340001aa
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[LRPoorBrakeResponse] # 左后后车制动响应差
mainCode = 0x340001ab
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ParkingBrakeNotRespond] # 驻车制动不响应
mainCode = 0x340001ac
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[HydraulicBrakePressureSensorFailure] # 液压制动压力传感器故障
mainCode = 0x340001ad
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[BrakeProportioningValveFailure] # 制动比例阀故障
mainCode = 0x340001ae
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[BrakeCmdOutOfRange] # 制动指令超限
mainCode = 0x340001af
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[GearCmdOutOfRange] # 档位指令超限
mainCode = 0x340001b0
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[ThroCmdOutOfRange] # 油门指令超限
mainCode = 0x340001b1
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[PoorForwardGearInsufficientBrake] # 进档抑制制动力不足
mainCode = 0x340001b2
auto_recovery = 1
fault_level = [1, 3, 3]

# 排查建议: 咨询XCMG

[SpdDiffWithLF] # 车速与左前轮不一致
mainCode = 0x340001c3
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[SpdDiffWithRF] # 车速与右前轮不一致
mainCode = 0x340001c4
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[SpdDiffWithLR] # 车速与左后轮不一致
mainCode = 0x340001c5
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG

[SpdDiffWithRR] # 车速与右后轮不一致
mainCode = 0x340001c6
auto_recovery = 0
fault_level = [3, 3, 3]

# 排查建议: 咨询XCMG


#-----------------------------------------[NHI,offset_HU16=0x3000]------------------------------------------#

#-----------------------------------------[TL,offset_HU16=0x3100]------------------------------------------#

#-----------------------------------------[MTCU,offset_HU16=0x3200]------------------------------------------#

#-----------------------------------------[HW,offset_HU16=0x3300]------------------------------------------#